DAC6-2731 : Added Select Address page
hmrc/crs-fatca-registration-frontend pull request #53
Opened 2023-11-13 14:19 UTC by AashuChauhanHmrc

2023-11-13 14:38 UTC, BriWak requested changes

2023-11-13 14:38 UTC, BriWak commented on app/models/IndSelectAddress.scala
This file isn't needed or used and should be removed.

2023-11-13 14:38 UTC, BriWak commented on test/models/IndSelectAddressSpec.scala
this spec can be removed as well

2023-11-13 14:38 UTC, BriWak commented on test/forms/IndSelectAddressFormProviderSpec.scala
> +import models.IndSelectAddress
remove this import as well

2023-11-13 16:46 UTC, AashuChauhanHmrc commented on test/models/IndSelectAddressSpec.scala
resolved comments

2023-11-14 07:34 UTC, BriWak submitted a review, later dismissed

2023-11-15 09:01 UTC, BriWak approved these changes

2023-11-15 09:01 UTC, merged